// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jLkZyFNJT8yEnRDPllt0AnctW5htqlc',
    appId: '1:928351569541:android:8b4c79b4895ff14cb50bec',
    messagingSenderId: '928351569541',
    projectId: 'qwerty-24d1c',
    databaseURL: 'https://qwerty-24d1c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qwerty-24d1c.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-h-zz0Sp4QDKMv9e14KO2V8CcUrJ7NTY',
    appId: '1:928351569541:web:6cae3fea2fa4ecb8b50bec',
    messagingSenderId: '928351569541',
    projectId: 'qwerty-24d1c',
    authDomain: 'qwerty-24d1c.firebaseapp.com',
    databaseURL: 'https://qwerty-24d1c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qwerty-24d1c.appspot.com',
  );

}